const { chromium } = require('playwright');
(async()=>{const b=await chromium.launch();const errs=[];
const p=await b.newPage({viewport:{width:390,height:844},deviceScaleFactor:2});p.on('pageerror',e=>errs.push(e.message));p.on('dialog',d=>d.accept());
await p.goto('http://localhost:8765/index.html');await p.evaluate(()=>localStorage.clear());await p.reload();await p.waitForTimeout(500);
const st=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('sqld.v1')).bm);
const qid=await p.$eval('.qmeta .qid',e=>e.textContent);
await p.click('.qmeta .bm');const b1=await p.textContent('.qmeta .bm');
await p.click('[data-nav="1"]');const qid2=await p.$eval('.qmeta .qid',e=>e.textContent);await p.click('.qmeta .bm');
await p.click('.tabs button[data-mode="concept"]');await p.waitForTimeout(200);
await p.click('#c-notin .blk .bm');await p.click('#c-win .blk:nth-of-type(3) .bm');
const s1=await st();
await p.click('.tabs button[data-mode="wrong"]');await p.waitForTimeout(150);
const seg=await p.$$eval('[data-src]',x=>x.map(e=>e.textContent));
await p.click('[data-src="bm"]');await p.waitForTimeout(150);
const bmView={first:await p.$eval('.qmeta .qid',e=>e.textContent),why:await p.$eval('.qtop .pill:not(.sub)',e=>e.textContent),cnt:await p.$eval('.cnt',e=>e.textContent)};
await p.click('.opt[data-i="0"]');await p.click('[data-nav="1"]');const stay=(await st()).q.length;
await p.click('[data-src="cbm"]');await p.waitForTimeout(150);
const cb={n:await p.$$eval('.blk-h h3',x=>x.map(e=>e.textContent))};
await p.screenshot({path:'/tmp/sqld-bm.png',fullPage:true});
await p.click('.blk-h .bm');await p.waitForTimeout(150);const cb2=await p.$$eval('.blk-h h3',x=>x.length);
await p.click('[data-src="wrong"]');const wrongOk=await p.$eval('h2',e=>e.textContent);
await p.click('.tabs button[data-mode="mock"]');await p.click('[data-set="1"]');const mockStar=await p.$$('.qmeta .bm');
console.log(JSON.stringify({qid,b1,qid2,s1,seg,bmView,stayAfterSolve:stay,cb,cb2,wrongOk,mockStar:mockStar.length,errs,w:await p.evaluate(()=>document.documentElement.scrollWidth)},null,1));await b.close();})();
